Publish 'What is data science'
realworlddatascience/realworlddatascience.github.io pull request #157
Opened 2024-02-16 13:39 UTC by brtarran

2024-02-16 13:44 UTC, brtarran commented
@jauerbach Site version ready for review

2024-02-17 17:16 UTC, jauerbach requested changes

2024-02-17 17:16 UTC, jauerbach commented on index.qmd
I would change to: Two popular data science algorithms -- naïve Bayes and eigen centrality -- are used to examine the difference between data scientists, statisticians, and other occupations.

2024-02-19 12:13 UTC, brtarran commented on index.qmd
Changed in 0b6a927

2024-02-19 12:46 UTC, merged